"""
Django settings for database project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import environ
from pathlib import Path
from datetime import timedelta
from django.utils import timezone

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environmental parameters loading
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*']

INTERNAL_IPS = [
    '127.0.0.1',  # Локальный доступ
    '192.168.0.0/16',
    'localhost'  # Пример диапазона для локальной сети
]

# Application definition

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_otp',
    'two_factor',
    'phonenumber_field',
    'users',
    'contractors',
    'projects',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'database.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'database.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",  # Убедитесь, что BASE_DIR верно настроен
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

FIELD_ENCRYPTION_KEY = env('ENC_KEY')

DEFAULT_CHARSET = "utf-8"

ALLOWED_FILE_EXTENSIONS = ['pdf',
                           'docx',
                           'xlsx',
                           'txt',
                           'doc',
                           'rtf',
                           'csv',
                           'jpeg',
                           'png',
                           'grs',
                           'mxl',
                           'geo',
                           'ppt',
                           'pptx'
                           'jpeg',
                           'jpg',
                           ]

# Настройки аутентификации
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',  # Использование сессионной аутентификации
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # Оставляем для проверки авторизации
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}

# Настройки Celery

CELERY_BROKER_URL = 'redis://redis:6379/0'  # Указываем Redis как брокера (0 - это номер базы данных Redis)
CELERY_ACCEPT_CONTENT = ['json']  # Формат сериализации задач
CELERY_TASK_SERIALIZER = 'json'  # Используем JSON для сериализации задач
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'  # Хранение результатов также в Redis
CELERY_TIMEZONE = 'Europe/Moscow'  # Устанавливаем часовой пояс

# Безопасность сети
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Стандартная сессия через базу данных
SESSION_COOKIE_NAME = 'sessionid'  # Название cookie для сессии
SESSION_COOKIE_SECURE = not DEBUG  # Использование HTTPS для cookies (важно для продакшн)
SESSION_COOKIE_HTTPONLY = False  # Защищает cookie от доступа через JavaScript
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Закрытие браузера = выход из системы
CSRF_COOKIE_SECURE = not DEBUG  # Защита от CSRF при передаче через HTTPS
CSRF_COOKIE_HTTPONLY = False  # Защита от XSS атак
CSRF_TRUSTED_ORIGINS = ['http://localhost:5012',  # Добавляем локальный адрес клиента
                        'http://127.0.0.1:5012', 'https://localhost:7065',
                        'https://127.0.0.1:7065', 'https://0.0.0.1', 'http://0.0.0.1']  # Можно указать доверенные источники

CSRF_COOKIE_NAME = "csrftoken"

CSRF_COOKIE_SAMESITE = "Lax"

ADMIN_URL = 'admin/'

SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 3600 * 12

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5012", "https://127.0.0.1:7065", 'http://localhost:5012', 'https://localhost:7065', 'https://0.0.0.1', 'http://0.0.0.1']
CORS_ALLOW_CREDENTIALS = True

#Почта

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'backendu@yandex.ru'  # почтовый адрес
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

DATE_FORMAT = 'd-m-Y'  # Формат: день-месяц-год
TIME_FORMAT = 'H:i:s'  # Можно добавить формат для времени, если нужно
DATETIME_FORMAT = 'd-m-Y H:i:s'  # Для комбинированного формата даты и времени