# Generated by Django 5.1.3 on 2024-11-16 14:24

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentalCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Полное наименование организации', max_length=150)),
                ('address', models.CharField(help_text='Адрес', max_length=250)),
                ('okfs', models.CharField(blank=True, help_text='ОКФС - Форма собственности', max_length=50, null=True)),
                ('okopf', models.CharField(blank=True, help_text='ОКОПФ - Организационно-правовая форма', max_length=100, null=True)),
                ('okogu', models.CharField(blank=True, help_text='ОКОГУ - Орган государственного управления', max_length=100, null=True)),
                ('inn', models.CharField(help_text='ИНН - Идентификационный номер налогоплательщика', max_length=12)),
                ('ogrn', models.CharField(help_text='ОГРН - Основной государственный регистрационный номер', max_length=13)),
                ('kpp', models.CharField(blank=True, help_text='КПП - Код причины постановки на учет', max_length=9, null=True)),
                ('okato', models.CharField(blank=True, help_text='ОКАТО - Код территории', max_length=100, null=True)),
                ('okpo', models.CharField(blank=True, help_text='ОКПО - Общероссийский классификатор предприятий и организаций', max_length=10, null=True)),
                ('oktmo', models.CharField(blank=True, help_text='ОКТМО - Общероссийский классификатор территорий муниципальных образований', max_length=100, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Контактный телефон', max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, help_text='Электронная почта', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Сайт компании', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubContractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Полное наименование организации', max_length=150)),
                ('inn', models.CharField(help_text='ИНН - Идентификационный номер налогоплательщика', max_length=12, null=True)),
                ('ogrn', models.CharField(help_text='ОГРН - Основной государственный регистрационный номер', max_length=13)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Контактный телефон', max_length=128, region=None)),
                ('email', models.EmailField(help_text='Электронная почта', max_length=254)),
            ],
        ),
    ]
