POST http://127.0.0.1:8000/u/api/login/
Content-Type: application/json

{"email": "bajenchik@smradnik.com", "password": "pwd1488"}

###

GET http://127.0.0.1:8000/u/api/test/
Content-Type: application/json

{}

###

GET http://127.0.0.1:8000/u/api/secure_test/
Content-Type: application/json
Cookie: access_token=<ваш access_token>

###

POST http://127.0.0.1:8000/u/api/logout/
Content-Type: application/json
Cookie: refresh_token=<ваш refresh_token>

###

GET http://127.0.0.1:8000/u/api/role_test/
Content-Type: application/json
Cookie: access_token=<ваш access_token>
Cookie: refresh_token=<ваш refresh_token>

{"role": "ADMIN"}

###
